language: node_js
node_js:
  - "5.0"
  - "4.1"
  - "4.0"

before_script:
  - npm install codecov

script:
  - npm test
  - curl -s https://en.wikipedia.org/wiki/Batman | node ./lib/cli.js

after_script:
  - ./node_modules/.bin/codecov
